### ISSUE TITLE
Add Gallery to CMS

### ISSUE THREAD

**Issue by ZackBradshaw** [Open-SGF/invisiblemanleadership.org#19]

**Comment by ZackBradshaw** [comment]
![2023-03-28 19_50_32-Invisible Man Wireframes – Figma](https://user-images.githubusercontent.com/21285642/228398613-d77e5e44-4e90-4f3d-a5f1-40e6ece8f301.png)

**Comment by joshuagoeke** [comment]
I did it! Zack merged it!
