### ISSUE TITLE
FE Desktop Hero

### ISSUE THREAD

**Issue by ZackBradshaw** [Open-SGF/invisiblemanleadership.org#4]
![image](https://user-images.githubusercontent.com/9029666/235810103-859180f2-fc2f-4f1b-8faf-dd06e5dffc8c.png)

Note: we need to support 4 separate images here. Not a single image that's been edited to look like this

**Comment by ethanzitting** [comment]
<img width="744" alt="Screenshot 2023-03-14 at 7 22 03 PM" src="https://user-images.githubusercontent.com/62777136/225171436-90fe6e0a-52f0-48b0-a85d-564190eb1398.png">
